In [55]:
import pandas as pd

In [56]:
dados = pd.read_csv('dados/nigeria_data.csv', sep=';')
dados

,Name,Year of establishment,Ownership,Category
0,"Federal College of Education (Technical), Asaba",1987.0,Federal Government,College of Education
1,"Federal College of Education, Kano",1961.0,Federal Government,College of Education
2,"Federal College of Education (Special), Oyo",1977.0,Federal Government,College of Education
3,"College of Education, Gindiri",1980.0,State Government,College of Education
4,"College of Education, Hong",1970.0,State Government,College of Education
...,...,...,...,...
1043,"Umuebe Farm College, Abakaliki, Ebonyi State",2010.0,Private,Vocational Enterprise
1044,"Unival Institute of Technology, Benin City",2015.0,Private,Vocational Enterprise
1045,"UTAGBA-UNO Vocational Enterprise Institute, Is...",2009.0,Private,Vocational Enterprise
1046,"Yenagoa Enterprise School, Yenagoa",2015.0,Private,Vocational Enterprise
1047,Young Men Christian Association (YMCA) Vocatio...,2012.0,Private,Vocational Enterprise

In [57]:
dados.head(10)

,Name,Year of establishment,Ownership,Category
0,"Federal College of Education (Technical), Asaba",1987.0,Federal Government,College of Education
1,"Federal College of Education, Kano",1961.0,Federal Government,College of Education
2,"Federal College of Education (Special), Oyo",1977.0,Federal Government,College of Education
3,"College of Education, Gindiri",1980.0,State Government,College of Education
4,"College of Education, Hong",1970.0,State Government,College of Education
5,"Tai Solarin College of Education, Ijebu-Ode",1978.0,State Government,College of Education
6,"College of Education, Ikere-Ekiti",1977.0,State Government,College of Education
7,"Ebonyi State College of Education, (T) Ikwo",2001.0,State Government,College of Education
8,"College of Education, Warri",1980.0,State Government,College of Education
9,"FCT College of Education, Zuba",1997.0,State Government,College of Education

In [58]:
type(dados)

pandas.core.frame.DataFrame

In [59]:
dados.Name

0         Federal College of Education (Technical), Asaba
1                      Federal College of Education, Kano
2             Federal College of Education (Special), Oyo
3                           College of Education, Gindiri
4                              College of Education, Hong
                              ...
1043        Umuebe Farm College, Abakaliki,  Ebonyi State
1044           Unival Institute of Technology, Benin City
1045    UTAGBA-UNO Vocational Enterprise Institute, Is...
1046                   Yenagoa Enterprise School, Yenagoa
1047    Young Men Christian Association (YMCA) Vocatio...
Name: Name, Length: 1048, dtype: object

In [60]:
dados.rename(columns={"Name": "Nome"}, inplace=True)
dados

,Nome,Year of establishment,Ownership,Category
0,"Federal College of Education (Technical), Asaba",1987.0,Federal Government,College of Education
1,"Federal College of Education, Kano",1961.0,Federal Government,College of Education
2,"Federal College of Education (Special), Oyo",1977.0,Federal Government,College of Education
3,"College of Education, Gindiri",1980.0,State Government,College of Education
4,"College of Education, Hong",1970.0,State Government,College of Education
...,...,...,...,...
1043,"Umuebe Farm College, Abakaliki, Ebonyi State",2010.0,Private,Vocational Enterprise
1044,"Unival Institute of Technology, Benin City",2015.0,Private,Vocational Enterprise
1045,"UTAGBA-UNO Vocational Enterprise Institute, Is...",2009.0,Private,Vocational Enterprise
1046,"Yenagoa Enterprise School, Yenagoa",2015.0,Private,Vocational Enterprise
1047,Young Men Christian Association (YMCA) Vocatio...,2012.0,Private,Vocational Enterprise

In [61]:
dados.columns = ['Nome', 'Ano_de_Criacao', 'Dono', 'Categoria']
dados

,Nome,Ano_de_Criacao,Dono,Categoria
0,"Federal College of Education (Technical), Asaba",1987.0,Federal Government,College of Education
1,"Federal College of Education, Kano",1961.0,Federal Government,College of Education
2,"Federal College of Education (Special), Oyo",1977.0,Federal Government,College of Education
3,"College of Education, Gindiri",1980.0,State Government,College of Education
4,"College of Education, Hong",1970.0,State Government,College of Education
...,...,...,...,...
1043,"Umuebe Farm College, Abakaliki, Ebonyi State",2010.0,Private,Vocational Enterprise
1044,"Unival Institute of Technology, Benin City",2015.0,Private,Vocational Enterprise
1045,"UTAGBA-UNO Vocational Enterprise Institute, Is...",2009.0,Private,Vocational Enterprise
1046,"Yenagoa Enterprise School, Yenagoa",2015.0,Private,Vocational Enterprise
1047,Young Men Christian Association (YMCA) Vocatio...,2012.0,Private,Vocational Enterprise

In [63]:
dados.drop('Private', axis=0, inplace=True)

KeyError: "['Private'] not found in axis"